### DISCUSSION TITLE
Missing types from sonarr dump-config

### DISCUSSION THREAD

**Discussion by ezekieldas** [buildarr/buildarr#195] [Q&A] [answered]
This is probably a bug but I'll start here.

I did a dump of sonnar like so:

`# docker exec -it buildarr buildarr sonarr dump-config http://localhost:8989 > sonarr.yml`

I'm using that exact output (`sonarr.yml`) in my `buildarr.yml` definition:

**buildarr.yml:**

```
includes:
  - sonarr.yml
```

**sonarr.yml:**

```
sonarr:
  hostname: localhost
  port: 8989
  protocol: http
  url_base: null
  api_key: foobar
  version: 3.0.10.1567
  settings:
    media_management:
      rename_episodes: true
```

But then on start `docker compose up -d` I see this error:

```
sonarr -> settings -> indexers -> definitions -> 1337x
  Discriminator 'type' is missing in value (type=value_error.discriminated_union.missing_discriminator; discriminator_key=type)
```

I found a similar definition in my `radarr.yml`, which included a `type:`. The `sonarr.yml` did not. So I manually entered this like so:

```
      definitions:
        1337x:
          type: torznab
          enable_rss: true
```

Must be sure to get the type correct, or this will present itself (but also offers allowed values):

```
sonarr -> settings -> indexers -> definitions -> 1337x
  No match for discriminator 'type' and value '1337x' (allowed values: 'fanzub', 'newznab', 'omgwtfnzbs', 'broadcasthenet', 'filelist', 'hdbits', 'iptorrents', 'nyaa', 'rarbg', 'torrentrssfeed', 'torrentleech', 'torznab') (type=value_error.discriminated_union.invalid_discriminator; discriminator_key=type; discriminator_value=1337x; allowed_values='fanzub', 'newznab', 'omgwtfnzbs', 'broadcasthenet', 'filelist', 'hdbits', 'iptorrents', 'nyaa', 'rarbg', 'torrentrssfeed', 'torrentleech', 'torznab')
```

I also found this `connect:` definition was missing a `type:` as well. So borrowing from the sonarr dump again, I manually added `type: telegram`:

```
    connect:
      definitions:
        telegrambot00:
          notification_triggers:
            on_grab: false
            [ ... ]
            on_application_update: true
          tags: []
          type: telegram
          bot_token: 123666:foobar
          chat_id: '123999'
          send_silently: false
```

With those corrects everything runs just fine now!
