### DISCUSSION TITLE
Re: Multiple configuration files

### DISCUSSION THREAD

**Discussion by ezekieldas** [buildarr/buildarr#210] [Show and tell]
I'll do a PR against the documentation on this but want to mention here for now. I found this really helpful for troubleshooting... 

The language on nested inclusion didn't really ring straight away. I had to play with this to see how it worked. 

https://buildarr.github.io/configuration/#multiple-configuration-files

To make the configs even more modular includes can be used to include sections of a config. Here's an example:

buildarr.yml:
```
buildarr:
  watch_config: true
  request_timeout: 90

includes:
  - prowlarr.yml
  - prowlarr.indexers.yml
  - prowlarr.apps.yml
  - radarr.yml
  - sonarr.yml
 ```

prowlarr.indexers.yml
```
prowlarr:
  settings:
    indexers:
      indexers:
        delete_unmanaged: false
        definitions:
          1337x:
 [ ... ]
```

prowlarr.apps.yml

```
prowlarr:
  settings:
    apps:
      applications:
        delete_unmanaged: false
        definitions:
          Sonarr:
 [ ... ]
```

**Comment by Callum027** [comment]
To give a very simple explanation of what nested inclusion is, it is when you include a file, into a file that is already included in another file.

To use your example, in `buildarr.yml` you would have:

```yaml
buildarr:
  watch_config: true
  request_timeout: 90

includes:
  - prowlarr.yml
  - radarr.yml
  - sonarr.yml
```

And then in `prowlarr.yml` you would have:

```yaml
includes:
  - prowlarr.indexers.yml
  - prowlarr.apps.yml
```

And then you'd have the `prowlarr.*.yml` files defined exactly the same.

`prowlarr.indexers.yml`:

```yaml
prowlarr:
  settings:
    indexers:
      indexers:
        delete_unmanaged: false
        definitions:
          1337x:
 [ ... ]
```

`prowlarr.apps.yml`:

```yaml
prowlarr:
  settings:
    apps:
      applications:
        delete_unmanaged: false
        definitions:
          Sonarr:
 [ ... ]
```

This should be equivalent to what you have defined in the OP.
