### ISSUE TITLE
Allow secret data (api keys, username-password) to be loaded from another file

### ISSUE THREAD

**Issue by rouke-broersma** [buildarr/buildarr#144]
I am trying to run buildarr in kubernetes using `gitops` and argocd. To safely store secret data in my git repo I encrypt them using sealed-secrets, which encrypts them in a way that can only be decrypted inside the kubernetes cluster. To be able to do this for buildarr I have to encrypt the complete configuration file every time I make a change, which means I have to keep the complete configuration file unencrypted somewhere on my system. It would be great if the secret data could be supplied in a separate file, so I can encrypt only the secret parts of the config.

**Comment by rouke-broersma** [comment]
I just realized I might easily be able to do this using includes, will test that.

**Comment by rouke-broersma** [comment]
With the following config:

buildarr.yml:

```
buildarr:
      watch_config: true
includes: 
- /prowlarr/prowlarr.yaml
- /prowlarr/secrets/api-key.yaml
```

prowlarr.yaml:

```
prowlarr:
  instances:
    prowlarr:
      hostname: prowlarr.prowlarr
      port: 80
      protocol: http
      settings:
        indexers:
          indexers:
            delete_unmanaged: false
            definitions:
              DrunkenSlug:
                type: newznab
                enable: true
                sync_profile: Standard
                redirect: false
                priority: 25
                query_limit: 25
                grab_limit: 5
                tags: []
                fields:
                  baseUrl: https://api.drunkenslug.com
                  apiPath: /api
                  additionalParameters: null
                  vipExpiration: ''
                  baseSettings.limitsUnit: Day
                includes:
                - /drunken-slug/secrets/api-key.yaml
```

prowlarr/secrets/api-key.yaml:

```
prowlarr:
  instances:
    prowlarr:
      api_key: xxxx
```

I get this error:


```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='prowlarr', port=80): Max retries exceeded with url: /api/v1/system/status (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7ff5c97fcd10>: Failed to resolve 'prowlarr' ([Errno -5] Name has no usable address)"))
```

This seems to suggest perhaps the config is not merged in the way I'm expecting?

**Comment by Callum027** [comment]
`includes` can only be defined on the top level of a file.

While `includes` *mostly* does recursive merging of configuration in the way you'd expect, definitions of resources such as indexers are the one exception where it doesn't. All indexer definitions should be defined in one file, and one file only.

You could define all of your regular settings in one file, and all of your indexers in one separate file, like so:

`buildarr.yml`:

```yaml
---

buildarr:
  watch_config: true

includes: 
  - prowlarr.yml
```

`prowlarr.yml`:

```yaml
---

includes:
  - prowlarr-secret.yml

prowlarr:
  instances:
    prowlarr:
      hostname: prowlarr.prowlarr
      port: 80
      protocol: http
      settings:
        ...  # Settings that do not need to be secret
```

`prowlarr-secret.yml`:

```yaml
---

prowlarr:
  instances:
    prowlarr:
      api_key: xxxx
      settings:
        indexers:
          definitions:
            ...
```

**Comment by Callum027** [comment]
If you have any issues using the above structure, let me know.

**Comment by rouke-broersma** [comment]
I see, thanks! How can I tell in which case I can't merge the config? I noticed in the docs that lists can't be merged and I would expect that since it's the same in helm, but definitions are not a list (type in yaml).

**Comment by Callum027** [comment]
Apologies, looks like I was actually mistaken in my comments above.

You actually can override parameters in resource (e.g. indexer) definitions in other files using `includes`.

For example, here are my two files I tried:

`prowlarr.yml`:

```yaml
---

includes:
  - prowlarr-2.yml

prowlarr:
  instances:
    prowlarr:
      api_key: xxxx
      settings:
        indexers:
          indexers:
            definitions:
              "Nyaa.si":
                type: nyaasi
                enable: true
                sync_profile: Standard
                redirect: false
                priority: 15
                grab_limit: 50  # Overridden to 104.
                query_limit: 10010
                tags:
                  - shows
                  - movies
                  - anime-shows
                  - anime-movies
                fields:
                  # baseUrl: https://nyaa.si/
                  torrentBaseSettings.seedRatio: null
                  prefer_magnet_links: true
```

```yaml
---

prowlarr:
  instances:
    prowlarr:
      settings:
        indexers:
          indexers:
            definitions:
              "Nyaa.si":
                type: nyaasi
                sync_profile: Standard
                grab_limit: 104  # Set to 50 in the original file
```

Buildarr picked `104`.

However, due to the limitation of individual configuration files being parsed individually by Buildarr once before merging them, I needed to add the required parameters for an indexer (`type` and `sync_profile`) to the second file as well.

I think if I figured out a way to remove this limitation it would work pretty much the way you'd expect.
