### ISSUE TITLE
Using latest docker image, buildarr seems to be using config KEY instead of Host: value for connecting.

### ISSUE THREAD

**Issue by gleepwurp** [buildarr/buildarr#175]
Hi!
Even though I have the following buildarr.yml configuration with an FQDN as a host, buildarr tries to use the config's key (sonarr) in order to connect to my instance, instead of the actual host.

Config:
```
...
sonarr:
  host: "sonarr.fizban.ca"
  port: 443
  protocol: "https"
```

buildarr execution log:

```
buildarr  | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sonarr', port=443): Max retries exceeded with url: /api/v3/system/status (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f61ca6a3910>: Failed to resolve 'sonarr' ([Errno -3] Try again)"))

```
It's picking of the either or both the https protocol and port 443, but not the host: value correcly.

buildarr  | 2024-02-14 19:52:57,200 buildarr:1 buildarr.cli.daemon [INFO] Buildarr version 0.7.1 (log level: INFO)

**Comment by gleepwurp** [comment]
Found the issue... Looked at the code, and the variable name should be `hostname`, and not just `host`.  The documentation shows `host` as the key to use, so the code might have been updated, and the docs still refer to the old key.  
IE: 
```
---

sonarr:
  host: "sonarr.example.com"
  port: 8989
  protocol: "http"
  settings:
    ...
```
