### ISSUE TITLE
Add functional tests for configuration merging on file load

### ISSUE THREAD

**Issue by Callum027** [buildarr/buildarr#203]
This feature works, but is not currently being covered in automated testing.

### Example

`prowlarr.yml`:

```yaml
---

includes:
  - prowlarr-2.yml

prowlarr:
  instances:
    prowlarr:
      api_key: xxxx
      settings:
        indexers:
          indexers:
            definitions:
              "Nyaa.si":
                type: nyaasi
                enable: true
                sync_profile: Standard
                redirect: false
                priority: 15
                grab_limit: 50  # Overridden in the included file.
                query_limit: 10010
                fields:
                  torrentBaseSettings.seedRatio: null
                  prefer_magnet_links: true
```

`prowlarr-2.yml`:

```yaml
---

prowlarr:
  instances:
    prowlarr:
      settings:
        indexers:
          indexers:
            definitions:
              "Nyaa.si":
                grab_limit: 104  # Override the value in the original file.
```
