### ISSUE TITLE
instructions and details on yaml configuration and placement

### ISSUE THREAD

**Issue by Tom-Neverwinter** [buildarr/buildarr#214]
I am not certain where to place the config and how my address is setup isnt stated. https://buildarr.github.io/configuration/

there is a hint on where to install the config based on the photo at the bottom but it still throws an error:
https://buildarr.github.io/installation/windows/

```
# buildarr.yml
---
buildarr:
  watch_config: true  # Watch for file changes and auto-reload
  update_days:
    - "monday"
    - "tuesday"
    - "wednesday"
    - "thursday"
    - "friday"
    - "saturday"
    - "sunday"
  update_times:
    - "03:00"  # Time to check for updates, can add more times

# Sonarr configuration
sonarr:
  hostname: "http://localhost:8989"  # Replace with your Sonarr host
  port: 8989  # Replace with your Sonarr port
  protocol: "http"  # Use "https" if applicable
  api_key: ""  # Your Sonarr API key

# Radarr configuration
radarr:
  hostname: "http://localhost:7878"  # Replace with your Radarr host
  port: 7878  # Replace with your Radarr port
  protocol: "http"  # Use "https" if applicable
  api_key: ""  # Your Radarr API key

# Lidarr configuration
lidarr:
  hostname: "http://localhost:8686"  # Replace with your Lidarr host
  port: 8686  # Replace with your Lidarr port
  protocol: "http"  # Use "https" if applicable
  api_key: ""  # Your Lidarr API key

# Prowlerr configuration
prowlerr:
  hostname: "http://localhost:9696"  # Replace with your Prowlerr host
  port: 9696  # Replace with your Prowlerr port
  protocol: "http"  # Use "https" if applicable
  api_key: ""  # Your Prowlerr API key


```

api key redacted for obvious reasons

the guide says: These Buildarr shortcuts read buildarr.yml from your home folder (e.g. C:\Users\<username>\buildarr.yml). however that does not seem to work either?

----------------------------------------------------------------------------------------------------------------------------------------

solved update python to 3.11 [I had it on 3.7] 

config had to look like this:
```
# buildarr.yml
---
buildarr:
  watch_config: true  # Watch for file changes and auto-reload
  update_days:
    - "monday"
    - "tuesday"
    - "wednesday"
    - "thursday"
    - "friday"
    - "saturday"
    - "sunday"
  update_times:
    - "03:00"  # Time to check for updates, can add more times

# Sonarr configuration
sonarr:
  hostname: "localhost"  # Replace with your Sonarr host
  port: 8989  # Replace with your Sonarr port
  protocol: "http"  # Use "https" if applicable
  api_key: "api"  # Your Sonarr API key

# Radarr configuration
radarr:
  hostname: "localhost"  # Replace with your Radarr host
  port: 7878  # Replace with your Radarr port
  protocol: "http"  # Use "https" if applicable
  api_key: "api"  # Your Radarr API key

# Lidarr configuration
lidarr:
  hostname: "localhost"  # Replace with your Lidarr host
  port: 8686  # Replace with your Lidarr port
  protocol: "http"  # Use "https" if applicable
  api_key: "api"  # Your Lidarr API key

# Prowlerr configuration
prowlerr:
  hostname: "localhost"  # Replace with your Prowlerr host
  port: 9696  # Replace with your Prowlerr port
  protocol: "http"  # Use "https" if applicable
  api_key: "api"  # Your Prowlerr API key
```
config installed to installation default installaer directory and it seems to accept it
"C:\Users\USER\AppData\Local\Programs\Buildarr"
