### ISSUE TITLE
No loaded plugins configured in Buildarr problem

### ISSUE THREAD

**Issue by EnjoyBacon7** [buildarr/buildarr#222]
After setting up my buildarr.yml file and dumping my sonarr config into a corresponding yml, running

`buildarr run`

crashes with the following error message:

"No loaded plugins configured in Buildarr"

Is this a known issue caused by common mistakes during setup?

**Comment by EnjoyBacon7** [comment]
It seems I was too hasty in opening an issue. The dump (and I) did not indent everything behind a `sonarr:` tag.

Wrong:
```
hostname: "sonarr.example.com"
port: 8989
protocol: "http"
```

Right: 
```
sonarr:
  hostname: "sonarr.example.com"
  port: 8989
  protocol: "http"
```
