### ISSUE TITLE
cant use instance name in prowlarr config

### ISSUE THREAD

**Issue by Dialgatrainer02** [buildarr/buildarr#228]
hello im trying to use instance same to configure sonarr and radarr in prowlarr and its not working and i dont know why 
here are my configs 
prowalrr.yml 
```
---
prowlarr:
  hostname: prowlarr
  port: 9696
  protocol: http
  url_base: null
  api_key: "{{ arrstack_instance_apikeys['prowlarr'] }}"
  image: lscr.io/linuxserver/prowlarr
  version: 1.21.2.4649
  settings:
    indexers:
      indexers:
        delete_unmanaged: false
        definitions:
          Badass Torrents:
            type: badasstorrents
            enable: true
            sync_profile: Standard
            redirect: false
            priority: 25
            query_limit: null
            grab_limit: null
            tags:
            - flaresolverr
            - privoxy
            fields:
              definitionFile: badasstorrents
              baseUrl: null
              baseSettings.limitsUnit: Day
              torrentBaseSettings.appMinimumSeeders: null
              torrentBaseSettings.seedRatio: null
              torrentBaseSettings.seedTime: null
              torrentBaseSettings.packSeedTime: null
              downloadlink: magnet
              downloadlink2: .torrent
            secret_fields: {}
          Internet Archive:
            type: internetarchive
            enable: true
            sync_profile: Standard
            redirect: false
            priority: 25
            query_limit: null
            grab_limit: null
            tags: []
            fields:
              definitionFile: internetarchive
              baseUrl: null
              baseSettings.limitsUnit: Day
              torrentBaseSettings.appMinimumSeeders: null
              torrentBaseSettings.seedRatio: null
              torrentBaseSettings.seedTime: null
              torrentBaseSettings.packSeedTime: null
              titleOnly: true
              noMagnet: false
              sort: created
              type: desc
            secret_fields: {}
      proxies:
        delete_unmanaged: false
        definitions:
          FlareSolverr:
            type: flaresolverr
            tags:
            - flaresolverr
            host_url: http://flaresolverr:8191/
            request_timeout: 60
          privoxy:
            type: http
            tags: 
              - privoxy
            hostname: qbittorrent
            port: 8080
            username: null
            password: null
    apps:
      applications:
        delete_unmanaged: false
        definitions:
          Radarr:
            type: radarr
            prowlarr_url: http://prowlarr:9696
            base_url: http://radarr-hd:7878
            instance_name: "radarr-hd"
          Sonarr:
            type: sonarr
            prowlarr_url: http://prowlarr:9696
            base_url: http://sonarr-hd:8989
            instance_name: "sonarr-hd"
      sync_profiles:
        delete_unmanaged: false
        definitions:
          Standard:
            enable_rss: true
            enable_interactive_search: true
            enable_automatic_search: true
            minimum_seeders: 1
    download_clients:
      delete_unmanaged: false
      definitions: {}
    notifications:
      delete_unmanaged: false
      definitions: {}
    tags:
      definitions:
      - flaresolverr
      - privoxy
    general:
      host:
        bind_address: '*'
        port: 9696
        ssl_port: 6969
        use_ssl: false
        ssl_cert_path: null
        ssl_cert_password: null
        url_base: null
        instance_name: Prowlarr
      security:
        authentication: form
        authentication_required: enabled
        username: olivia
        password: {{ arrstack_password }}
        certificate_validation: enabled
      proxy:
        enable: false
        proxy_type: http
        hostname: null
        port: 8080
        username: null
        password: null
        ignored_addresses: []
        bypass_proxy_for_local_addresses: true
      logging:
        log_level: INFO
      analytics:
        send_anonymous_usage_data: true
      updates:
        branch: master
        automatic: false
        mechanism: docker
        script_path: null
      backup:
        folder: Backups
        interval: 7
        retention: 28
    ui:
      first_day_of_week: sunday
      week_column_header: month-first
      short_date_format: word-month-first
      long_date_format: month-first
      time_format: twelve-hour
      show_relative_dates: true
      enable_color_impaired_mode: false
      theme: auto
      ui_language: en

```
sonarr.yml
```
---
sonarr-hd:
  hostname: sonarr-hd
  port: 8989
  protocol: http
  url_base: null
  api_key: "{{ arrstack_instance_apikeys['sonarr-hd'] }}"
  version: 4.0.8.1874
  settings:
    media_management:
      rename_episodes: true
      replace_illegal_characters: true
      standard_episode_format: '{Series TitleYear} - S{season:00}E{episode:00} - {Episode
        CleanTitle} [{Custom Formats }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}{[Mediainfo
        AudioCodec}{ Mediainfo AudioChannels]}{[MediaInfo VideoCodec]}{-Release Group}'
      daily_episode_format: '{Series TitleYear} - {Air-Date} - {Episode CleanTitle}
        [{Custom Formats }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}{[Mediainfo
        AudioCodec}{ Mediainfo AudioChannels]}{[MediaInfo VideoCodec]}{-Release Group}'
      anime_episode_format: '{Series TitleYear} - S{season:00}E{episode:00} - {absolute:000}
        - {Episode CleanTitle} [{Custom Formats }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}[{MediaInfo
        VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo
        AudioChannels}]{MediaInfo AudioLanguages}{-Release Group}'
      series_folder_format: '{Series TitleYear} [tvdbid-{TvdbId}]'
      season_folder_format: Season {season:00}
      specials_folder_format: Specials
      multiepisode_style: prefixed-range
      create_empty_series_folders: false
      delete_empty_folders: true
      episode_title_required: always
      skip_free_space_check: false
      minimum_free_space: 100
      use_hardlinks: true
      import_extra_files: false
      unmonitor_deleted_episodes: true
      propers_and_repacks: do-not-prefer
      analyze_video_files: true
      rescan_series_folder_after_refresh: always
      change_file_date: none
      recycling_bin: null
      recycling_bin_cleanup: 7
      set_permissions: false
      chmod_folder: drwxr-xr-x
      chown_group: null
      root_folders:
      - /data/media/tv-hd
    profiles:
      quality_profiles:
        definitions:
          Web-HD:
            upgrades_allowed: true
            qualities:
            - name: Blurray/WEB 1080p
              members:
              - WEBDL-1080p
              - WEBRip-1080p
              - Bluray-1080p
              - Bluray-1080p Remux
              - Bluray-720p
            upgrade_until: Blurray/WEB 1080p
      language_profiles:
        definitions:
          Deprecated:
            upgrades_allowed: true
            languages:
            - english
            upgrade_until: english
      delay_profiles:
        definitions:
        - preferred_protocol: usenet-prefer
          usenet_delay: 0
          torrent_delay: 0
          bypass_if_highest_quality: true
          tags: []
      release_profiles:
        definitions: {}
    quality:
      trash_id: "bef99584217af744e404ed44a33af589"
    download_clients:
      delete_unmanaged: true
      enable_completed_download_handling: true
      redownload_failed: true
      definitions:
        qBittorrent (hd):
          enable: true
          priority: 1
          remove_completed_downloads: true
          remove_failed_downloads: true
          tags: []
          host: qbittorrent
          port: 8080
          use_ssl: false
          url_base: null
          username: olivia
          password: {{ arrstack_password }}
          category: tv-hd
          postimport_category: null
          recent_priority: last
          older_priority: last
          initial_state: start
          sequential_order: false
          first_and_last_first: false
      remote_path_mappings:
        definitions: []
    import_lists:
      definitions: {}
    connect:
      definitions: {}
    metadata:
      kodi_emby:
        enable: false
        series_metadata: true
        series_metadata_url: false
        episode_metadata: true
        series_images: true
        season_images: true
        episode_images: true
      roksbox:
        enable: false
        episode_metadata: true
        series_images: true
        season_images: true
        episode_images: true
      wdtv:
        enable: false
        episode_metadata: true
        series_images: true
        season_images: true
        episode_images: true
    tags:
      definitions: []
    general:
      host:
        bind_address: '*'
        port: 8989
        ssl_port: 9898
        use_ssl: false
        url_base: null
        instance_name: sonarr-hd
      security:
        authentication: form
        authentication_required: enabled
        username: olivia
        password: {{ arrstack_password }}
        certificate_validation: enabled
      proxy:
        enable: false
        proxy_type: http
        hostname: null
        port: 8080
        username: null
        password: null
        ignored_addresses: []
        bypass_proxy_for_local_addresses: true
      logging:
        log_level: INFO
      analytics:
        send_anonymous_usage_data: true
      updates:
        branch: main
        automatic: false
        mechanism: docker
        script_path: null
      backup:
        folder: Backups
        interval: 7
        retention: 28
    ui:
      first_day_of_week: sunday
      week_column_header: month-first
      short_date_format: word-month-first
      long_date_format: month-first
      time_format: twelve-hour
      show_relative_dates: true
      enable_color_impaired_mode: false

```
radarr.yml
```
---
radarr-hd:
  hostname: radarr-hd
  port: 7878
  protocol: http
  url_base: null
  api_key: "{{ arrstack_instance_apikeys['radarr-hd'] }}"
  version: 5.8.3.8933
  image: lscr.io/linuxserver/radarr
  settings:
    media_management:
      rename_movies: true
      replace_illegal_characters: true
      colon_replacement: delete
      standard_movie_format: '{Movie CleanTitle} {(Release Year)} [tmdbid-{TmdbId}]
        - {Edition Tags }{[Custom Formats]}{[Quality Full]}{[MediaInfo 3D]}{[MediaInfo
        VideoDynamicRangeType]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels]}{[Mediainfo
        VideoCodec]}{-Release Group}'
      movie_folder_format: '{Movie CleanTitle} ({Release Year}) [tmdbid-{TmdbId}]'
      create_missing_movie_folders: false
      delete_empty_folders: false
      skip_free_space_check: false
      minimum_free_space: 100
      use_hardlinks: true
      import_using_script: false
      import_script_path: null
      import_extra_files: false
      unmonitor_deleted_movies: false
      propers_and_repacks: do-not-prefer
      analyze_video_files: true
      rescan_folder_after_refresh: always
      change_file_date: none
      recycling_bin: null
      recycling_bin_cleanup: 7
      set_permissions: false
      chmod_folder: drwxr-xr-x
      chown_group: null
      root_folders:
      - /data/media/movie-hd
    profiles:
      quality_profiles:
        delete_unmanaged: false
        definitions:
          HD-1080p:
            upgrades_allowed: true
            qualities:
            - name: Bluray/WEB 1080p
              members:
              - Bluray-720p
              - WEBRip-1080p
              - Bluray-1080p
              - Remux-1080p
              - WEBDL-1080p
            upgrade_until_quality: Bluray/WEB 1080p
            minimum_custom_format_score: 0
            upgrade_until_custom_format_score: 0
            custom_formats:
            - name: HD Bluray Tier 01
              score: 1800
            - name: HD Bluray Tier 02
              score: 1750
            - name: HD Bluray Tier 03
              score: 1700
            - name: WEB Tier 01
              score: 1700
            - name: WEB Tier 02
              score: 1650
            - name: WEB Tier 03
              score: 1600
            - name: Repack3
              score: 7
            - name: Repack2
              score: 6
            - name: Repack/Proper
              score: 5
            - name: AV1
              score: -1000
            - name: BR-DISK
              score: -1000
            - name: Bad Dual Groups
              score: -1000
            - name: DV (WEBDL)
              score: -1000
            - name: DV HDR10+ Boost
              score: -1000
            - name: Extras
              score: -1000
            - name: HDR10+ Boost
              score: -1000
            - name: LQ
              score: -1000
            - name: LQ (Release Title)
              score: -1000
            - name: No-RlsGroup
              score: -1000
            - name: Obfuscated
              score: -1000
            - name: Retags
              score: -1000
            - name: Scene
              score: -1000
            - name: Upscaled
              score: -1000
            - name: VP9
              score: -1000
            - name: x265 (HD)
              score: -1000
            language: english
      delay_profiles:
        definitions:
        - preferred_protocol: usenet-prefer
          usenet_delay: 0
          torrent_delay: 0
          bypass_if_highest_quality: true
          tags: []
        delete_unmanaged: false
    quality:
      trash_id: aed34b9f60ee115dfa7918b742336277
    custom_formats:
      delete_unmanaged: false
      definitions:
        AV1:
          trash_id: cae4ca30163749b891686f95532519bd
        BR-DISK:
          trash_id: ed38b889b31be83fda192888e2286d83
        LQ:
          trash_id: 90a6f9a284dff5103f6346090e6280c8
        LQ (Release Title):
          trash_id: e204b80c87be9497a8a6eaff48f72905
        x265 (HD):
          trash_id: dc98083864ea246d05a42df0d05f81cc
        Upscaled:
          trash_id: bfd8eb01832d646a0a89c4deb46f8564
        Extras:
          trash_id: 0a3f082873eb454bde444150b70253cc
        Bad Dual Groups:
          trash_id: b6832f586342ef70d9c128d40c07b872
        DV (WEBDL):
          trash_id: 923b6abef9b17f937fab56cfcf89e1f1
        HDR10+ Boost:
          trash_id: b17886cb4158d9fea189859409975758
        DV HDR10+ Boost:
          trash_id: 55a5b50cb416dea5a50c4955896217ab
        No-RlsGroup:
          trash_id: ae9b7c9ebde1f3bd336a8cbd1ec4c5e5
        Obfuscated:
          trash_id: 7357cf5161efbf8c4d5d0c30b4815ee2
        Retags:
          trash_id: 5c44f52a8714fdd79bb4d98e2673be1f
        Scene:
          trash_id: f537cf427b64c38c8e36298f657e4828
        VP9:
          trash_id: ae4cfaa9283a4f2150ac3da08e388723
        INTERNAL:
          trash_id:  182fa1c42a2468f8488e6dcf75a81b81
        SDR:
          trash_id: 9c38ebb7384dada637be8899efa68e6f
        DV (Disk):
          trash_id: f700d29429c023a5734505e77daeaea7
        HFR:
          trash_id: 73613461ac2cea99d52c4cd6e177ab82
        Repack/Proper:
          trash_id: e7718d7a3ce595f289bfee26adc178f5
        Repack2:
          trash_id: ae43b294509409a6a13919dedd4764c4
        Repack3:
          trash_id: 5caaaa1c08c1742aa4342d8c4cc463f2
        WEB Tier 01:
          trash_id: c20f169ef63c5f40c2def54abaf4438e
        WEB Tier 02:
          trash_id: 403816d65392c79236dcb6dd591aeda4
        WEB Tier 03:
          trash_id: af94e0fe497124d1f9ce732069ec8c3b
        HD Bluray Tier 03:
          trash_id: 5608c71bcebba0a5e666223bae8c9227
        HD Bluray Tier 02:
          trash_id: c20c8647f2746a1f4c4262b0fbbeeeae
        HD Bluray Tier 01:
          trash_id: ed27ebfef2f323e964fb1f61391bcb35
    download_clients:
      delete_unmanaged: true
      definitions:
        qBittorrent:
          enable: true
          remove_completed_downloads: true
          remove_failed_downloads: true
          priority: 1
          tags: []
          type: qbittorrent
          hostname: qbittorrent
          port: 8080
          use_ssl: false
          url_base: null
          username: olivia
          password: {{ arrstack_password }}
          category: radarr-hd
          postimport_category: null
          recent_priority: last
          older_priority: last
          initial_state: start
          sequential_order: false
          first_and_last_first: false
    notifications:
      delete_unmanaged: false
      definitions: {}
    metadata:
      certification_country: us
      emby_legacy:
        enable: false
        movie_metadata: true
      kodi_emby:
        enable: false
        movie_metadata: true
        movie_metadata_url: false
        movie_metadata_language: english
        movie_images: true
        use_movie_nfo: false
        add_collection_name: true
      roksbox:
        enable: false
        movie_metadata: true
        movie_images: true
      wdtv:
        enable: false
        movie_metadata: true
        movie_images: true
    tags:
      definitions: []
    general:
      host:
        bind_address: '*'
        port: 7878
        ssl_port: 9898
        use_ssl: false
        ssl_cert_path: null
        ssl_cert_password: null
        url_base: null
        instance_name: radarr-hd
      security:
        authentication: form
        authentication_required: enabled
        username: olivia
        password: {{ arrstack_password }}
        certificate_validation: enabled
      proxy:
        enable: false
        proxy_type: http
        hostname: null
        port: 8080
        username: null
        password: null
        ignored_addresses: []
        bypass_proxy_for_local_addresses: true
      logging:
        log_level: INFO
      analytics:
        send_anonymous_usage_data: true
      updates:
        branch: master
        automatic: false
        mechanism: docker
        script_path: null
      backup:
        folder: Backups
        interval: 7
        retention: 28
    ui:
      first_day_of_week: sunday
      week_column_header: month-first
      runtime_format: hours-minutes
      short_date_format: word-month-first
      long_date_format: month-first
      time_format: twelve-hour
      show_relative_dates: true
      theme: auto
      enable_color_impaired_mode: false
      movie_info_language: english
      ui_language: english
  
```

buildarr logs (from docker)
```
2024-08-17 10:04:35,299 buildarr:1 buildarr.cli.daemon [INFO] Reloading config
2024-08-17 10:04:35,299 buildarr:1 buildarr.cli.daemon [INFO] Loading configuration file '/config/buildarr.yml'
2024-08-17 10:04:35,359 buildarr:1 buildarr.cli.daemon [ERROR] Unexpected exception occurred while handling config file event: 4 validation errors for Config
prowlarr -> settings -> apps -> applications -> definitions -> Radarr -> RadarrApplication -> instance_name
  target instance 'radarr-hd' not defined in plugin 'radarr' configuration (type=value_error)
prowlarr -> settings -> apps -> applications -> definitions -> Radarr -> RadarrApplication -> api_key
  required when 'instance_name' is not defined (type=value_error)
prowlarr -> settings -> apps -> applications -> definitions -> Sonarr -> SonarrApplication -> instance_name
  target instance 'sonarr-hd' not defined in plugin 'sonarr' configuration (type=value_error)
prowlarr -> settings -> apps -> applications -> definitions -> Sonarr -> SonarrApplication -> api_key
  required when 'instance_name' is not defined (type=value_error)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 331, in _watch_config_reload
    self._initial_run()
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 197, in _initial_run
    self._load_config()
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 156, in _load_config
    load_config(self.config_path)
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/load.py", line 94, in load_config
    state.config = model(**config)
                   ^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for Config
prowlarr -> settings -> apps -> applications -> definitions -> Radarr -> RadarrApplication -> instance_name
  target instance 'radarr-hd' not defined in plugin 'radarr' configuration (type=value_error)
prowlarr -> settings -> apps -> applications -> definitions -> Radarr -> RadarrApplication -> api_key
  required when 'instance_name' is not defined (type=value_error)
prowlarr -> settings -> apps -> applications -> definitions -> Sonarr -> SonarrApplication -> instance_name
  target instance 'sonarr-hd' not defined in plugin 'sonarr' configuration (type=value_error)
prowlarr -> settings -> apps -> applications -> definitions -> Sonarr -> SonarrApplication -> api_key
  required when 'instance_name' is not defined (type=value_error)
2024-08-17 10:04:35,361 buildarr:1 buildarr.cli.daemon [INFO] Buildarr ready.
2024-08-17 10:04:37,299 buildarr:1 buildarr.cli.daemon [INFO] Config file '/config/radarr.yml' has been recreated
2024-08-17 10:04:37,300 buildarr:1 buildarr.cli.daemon [INFO] Reloading config
2024-08-17 10:04:37,300 buildarr:1 buildarr.cli.daemon [INFO] Loading configuration file '/config/buildarr.yml'
2024-08-17 10:04:37,363 buildarr:1 buildarr.cli.daemon [ERROR] Unexpected exception occurred while handling config file event: 4 validation errors for Config
prowlarr -> settings -> apps -> applications -> definitions -> Radarr -> RadarrApplication -> instance_name
2024-08-17 10:04:37,363 buildarr:1 buildarr.cli.daemon [INFO] Buildarr ready.
  target instance 'radarr-hd' not defined in plugin 'radarr' configuration (type=value_error)
prowlarr -> settings -> apps -> applications -> definitions -> Radarr -> RadarrApplication -> api_key
  required when 'instance_name' is not defined (type=value_error)
prowlarr -> settings -> apps -> applications -> definitions -> Sonarr -> SonarrApplication -> instance_name
  target instance 'sonarr-hd' not defined in plugin 'sonarr' configuration (type=value_error)
prowlarr -> settings -> apps -> applications -> definitions -> Sonarr -> SonarrApplication -> api_key
  required when 'instance_name' is not defined (type=value_error)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 331, in _watch_config_reload
    self._initial_run()
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 197, in _initial_run
    self._load_config()
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 156, in _load_config
    load_config(self.config_path)
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/load.py", line 94, in load_config
    state.config = model(**config)
                   ^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for Config
prowlarr -> settings -> apps -> applications -> definitions -> Radarr -> RadarrApplication -> instance_name
  target instance 'radarr-hd' not defined in plugin 'radarr' configuration (type=value_error)
prowlarr -> settings -> apps -> applications -> definitions -> Radarr -> RadarrApplication -> api_key
  required when 'instance_name' is not defined (type=value_error)
prowlarr -> settings -> apps -> applications -> definitions -> Sonarr -> SonarrApplication -> instance_name
  target instance 'sonarr-hd' not defined in plugin 'sonarr' configuration (type=value_error)
prowlarr -> settings -> apps -> applications -> definitions -> Sonarr -> SonarrApplication -> api_key
  required when 'instance_name' is not defined (type=value_error)
```
