### ISSUE TITLE
`BaseIntEnum` is not handled properly in the Buildarr config parsing

### ISSUE THREAD

**Issue by Callum027** [buildarr/buildarr#91]
The following bugs occur in the current version of Buildarr:

* [x] `BaseIntEnum` has no specific handlers in the default decoder and formatting functions
* [x] ~~When `BaseIntEnum` objects are exported using the JSON/YAML encoder, the `BaseIntEnum` encoder does not get used as `BaseIntEnum` is a subclass of `int`, so the default behaviour is used:~~
  ```yaml
  jellyseerr:
    ...
    settings:
      ...
      users:
        default_permissions:
        - 1048576  # Should be 'MANAGE-ISSUES'
        - 32  # Should be 'REQUEST'
  ```
